version: '3.9'

services:
  hospitalapi:
    image: shahzod1999/hospitalapi-test
    container_name: hospitalapi
    restart: always
    ports:
      - "80:5000"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=Hospital;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hospitaldb
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - hospital_data:/var/opt/mssql

volumes:
  hospital_data:
