name: Build and Test and Dockerize and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore
      - run: dotnet test --configuration Release
     
     
  dockerize:
    needs: test
    runs-on: ubuntu-latest   
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}  
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/hospitalapi-test .
      - name: Push Docker image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/hospitalapi-test
      
  deploy:    
    name: Deploy Hospital api  
    needs: dockerize
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy .NET app
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up -d --no-deps --build hospitalapi